# Generated by Django 4.0 on 2024-02-19 17:47

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='https://d12uotnmkhw4d2.cloudfront.net/blank.png', max_length=5000, null=True, upload_to=backend.models.rename_media_file),
        ),
        migrations.AlterField(
            model_name='user',
            name='blink_board_image',
            field=models.FileField(default='https://d12uotnmkhw4d2.cloudfront.net/blank.png', max_length=5000, null=True, upload_to=backend.models.rename_media_file),
        ),
    ]
